<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.0 on win32)" generated="20201126 01:29:42.273" rpa="false">
<suite id="s1" name="TC 005" source="C:\Users\SHANMUGAVEL R\PycharmProjects\RobotAutomation\TC_005.robot">
<test id="s1-t1" name="Login &amp; Sign Up Forms test">
<kw name="Open Browser">
<arguments>
<arg>http://www.thetestingworld.com/testings</arg>
<arg>Chrome</arg>
</arguments>
<msg timestamp="20201126 01:29:42.297" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20201126 01:29:42.297" endtime="20201126 01:29:42.297"></status>
</kw>
<status status="FAIL" starttime="20201126 01:29:42.297" endtime="20201126 01:29:42.297" critical="yes">No keyword with name 'Open Browser' found.</status>
</test>
<doc>A test suite with a single test for Login &amp; Sign Up Forms
Created by hats' Robotcorder</doc>
<status status="FAIL" starttime="20201126 01:29:42.273" endtime="20201126 01:29:42.297"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TC 005">TC 005</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20201126 01:29:42.297" level="ERROR">Error in file 'C:\Users\SHANMUGAVEL R\PycharmProjects\RobotAutomation\TC_005.robot' on line 4: Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Program Files\Python39\Scripts\robot.exe
  c:\program files\python39\python39.zip
  c:\program files\python39\DLLs
  c:\program files\python39\lib
  c:\program files\python39
  C:\Users\SHANMUGAVEL R\AppData\Roaming\Python\Python39\site-packages
  c:\program files\python39\lib\site-packages</msg>
</errors>
</robot>
